name: deploy and publish

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # if: github.repository == 'SocialSisterYi/bilibili-API-collect'
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v6
      with:
        node-version: 22
        cache: yarn
    - name: Build with yarn
      run: yarn && yarn build
    - name: Commit & Push
      run: |
        cd .vuepress/dist/
        git init -b gh_pages
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git remote add origin https://user:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git add -A .
        git commit -m "generated"
        git push -fu origin gh_pages
